### PR TITLE
do you have donate button?

### PR DESCRIPTION
**Pull request by nikolaev-dev**

### CODE REVIEW

**Comment by iam-py-test** [comment]
@nikolaev-dev You might want to open an issue about this.
According to https://github.com/raxod502/python-in-a-box/commit/150a2d53d5fe122df15e91c62fc4153d9aea67d9#commitcomment-51853394 issues have been reenabled.

**Comment by raxod502** [comment]
Thanks for your support. Right now I'm not looking for donations, though if you'd like to put your money to a similar cause, you might consider sending something to the [Electronic Frontier Foundation](https://www.eff.org/).

**Comment by raxod502** [comment]
Riju is back online, with source code at https://github.com/raxod502/riju. As I mention in the README, I'm still not in need of donations, but since a number of people asked me about it, I set up a Patreon page: https://www.patreon.com/riju. Proceeds from that would be used to cover hosting costs, or in the unlikely event that there are more donations than my AWS bill, the extra would be donated to the EFF.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)

**Pull request closed without merging**
